# Generated by Django 4.2.25 on 2025-11-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('author', models.CharField(max_length=100, verbose_name='글쓴이')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('content', models.TextField(verbose_name='내용')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '견적문의',
                'verbose_name_plural': '견적문의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('author', models.CharField(max_length=100, verbose_name='글쓴이')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '자주하는 질문',
                'verbose_name_plural': '자주하는 질문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('author', models.CharField(max_length=100, verbose_name='글쓴이')),
                ('content', models.TextField(verbose_name='내용')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/', verbose_name='첨부파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-created_at'],
            },
        ),
    ]
